### ISSUE TITLE
[E8-08] Update Profile UI: Default Clipboard Profile + 4 Visible Profiles Limit

### ISSUE THREAD

**Issue by lsmod** [lsmod/DictaClerk#44]
## 📋 Description

Redesign the profile system to include a **default "Clipboard" profile** as Profile 1 that bypasses GPT-4 formatting, and limit the settings interface to show **maximum 4 user-configurable profiles**. This creates a cleaner UX where users have one direct clipboard option plus 4 custom formatting profiles.

**Current behavior:**
- Profile buttons 1-5 all have custom text/names
- All profiles can be configured in settings
- No "direct copy" option without formatting

**Target behavior:**
- **Profile 1**: Fixed clipboard icon (📋) - direct copy without GPT-4 processing
- **Profiles 2-5**: User-configurable with custom names and formatting
- **Settings**: Show only profiles 2-5 for editing (Profile 1 is system-defined)

## 🎯 Objective

Create an intuitive profile system where Profile 1 serves as a reliable "direct copy" option while Profiles 2-5 provide customizable GPT-4 formatting. This ensures users always have a fallback option and reduces cognitive load with a predictable first option.

#### 1. **Update Profile Data Structure**
```rust
// src/profile/types.rs or relevant profile definitions
impl Profile {
    pub fn is_clipboard_profile(&self) -> bool {
        self.id == "1"
    }
    
    pub fn should_use_gpt_formatting(&self) -> bool {
        !self.is_clipboard_profile() && !self.prompt.is_empty()
    }
}

// Ensure Profile 1 always exists in the system
pub fn ensure_clipboard_profile(profiles: &mut Vec<Profile>) {
    if !profiles.iter().any(|p| p.id == "1") {
        profiles.insert(0, Profile {
            id: "1".to_string(),
            name: "Clipboard".to_string(),
            description: "Copy transcription directly to clipboard without formatting".to_string(),
            prompt: "".to_string(),
            input_example: None,
            output_example: None,
            shortcut: None,
            visible: true,
        });
    }
}
```

#### 2. **Update Profile Loading Logic**
```rust
// src/commands/profiles.rs or relevant profile commands
#[tauri::command]
pub async fn load_profiles() -> Result<ProfileCollection, String> {
    let mut profiles = /* existing profile loading logic */;
    
    // Ensure clipboard profile always exists as Profile 1
    ensure_clipboard_profile(&mut profiles.profiles);
    
    Ok(profiles)
}
```

#### 3. **Update Profile Button Rendering**
```tsx
// src/components/ProfileButtons.tsx
const ProfileButton = ({ profile, isActive, onSelect }: ProfileButtonProps) => {
  const isClipboardProfile = profile.id === '1';
  
  return (
    <button
      className={`profile-button ${isActive ? 'active' : ''} ${isClipboardProfile ? 'clipboard-profile' : ''}`}
      onClick={() => onSelect(profile.id)}
      aria-label={isClipboardProfile ? 'Clipboard - Direct copy' : `Profile: ${profile.name}`}
    >
      {isClipboardProfile ? (
        <Clipboard size={16} className="clipboard-icon" />
      ) : (
        <span className="profile-text">{profile.name}</span>
      )}
      
      {/* Show shortcut if available */}
      {profile.shortcut && (
        <span className="profile-shortcut">{profile.shortcut}</span>
      )}
    </button>
  );
};
```

#### 4. **Update Settings Interface**
```tsx
// src/components/SettingsSheet.tsx - Profile Overview section
const SettingsOverview = () => {
  const { profiles } = useProfiles();
  
  // Filter out Profile 1 (clipboard) from settings view
  const editableProfiles = profiles.filter(p => p.id !== '1').slice(0, 4);
  const clipboardProfile = profiles.find(p => p.id === '1');
  
  return (
    <div className="settings-content">
      {/* Clipboard Profile - Read-only display */}
      <div className="clipboard-profile-section">
        <h3>Default Profile</h3>
        <div className="profile-row clipboard-profile-row">
          <div className="profile-info">
            <Clipboard size={16} />
            <span>Clipboard (Direct Copy)</span>
            <span className="profile-description">
              Copies transcription directly without GPT-4 formatting
            </span>
          </div>
          <div className="profile-status">
            <Check size={14} className="text-green-400" />
            <span>Always Available</span>
          </div>
        </div>
      </div>

      {/* User-configurable profiles (2-5) */}
      <div className="user-profiles-section">
        <div className="section-header">
          <h3>Custom Profiles</h3>
          <span className="profile-count">{editableProfiles.length}/4</span>
        </div>
        
        <DndContext onDragEnd={handleDragEnd}>
          <SortableContext items={editableProfiles} strategy={verticalListSortingStrategy}>
            {editableProfiles.map((profile) => (
              <SortableProfileRow
                key={profile.id}
                profile={profile}
                onEdit={() => navigateToEditor(profile.id)}
                onToggleVisibility={() => toggleProfileVisibility(profile.id)}
                onDelete={() => deleteProfile(profile.id)}
              />
            ))}
          </SortableContext>
        </DndContext>

        {editableProfiles.length < 4 && (
          <button 
            className="add-profile-button"
            onClick={() => navigateToEditor('new')}
          >
            <Plus size={16} />
            Add Profile ({editableProfiles.length}/4)
          </button>
        )}
      </div>
    </div>
  );
};
```

#### 5. **Update Profile Context Logic**
```tsx
// src/contexts/ProfileContext.tsx
export const useProfiles = () => {
  // ... existing context logic
  
  const getVisibleProfiles = useCallback(() => {
    const clipboard = profiles.find(p => p.id === '1');
    const userProfiles = profiles
      .filter(p => p.id !== '1' && p.visible)
      .slice(0, 4);
    
    return clipboard ? [clipboard, ...userProfiles] : userProfiles;
  }, [profiles]);
  
  const isClipboardProfile = useCallback((profileId: string) => {
    return profileId === '1';
  }, []);
  
  return {
    // ... existing returns
    getVisibleProfiles,
    isClipboardProfile,
    editableProfiles: profiles.filter(p => p.id !== '1').slice(0, 4),
  };
};
```

#### 6. **Update CSS Styling**
```css
/* src/styles.css - Profile button styles */
.profile-button.clipboard-profile {
  background: rgba(0, 255, 204, 0.1);
  border: 1px solid rgba(0, 255, 204, 0.3);
  position: relative;
}

.profile-button.clipboard-profile::before {
  content: '';
  position: absolute;
  top: 2px;
  right: 2px;
  width: 6px;
  height: 6px;
  background: #00ffcc;
  border-radius: 50%;
  opacity: 0.7;
}

.profile-button.clipboard-profile:hover {
  background: rgba(0, 255, 204, 0.15);
  border-color: rgba(0, 255, 204, 0.5);
}

.profile-button.clipboard-profile.active {
  background: rgba(0, 255, 204, 0.2);
  border-color: #00ffcc;
  box-shadow: 0 0 12px rgba(0, 255, 204, 0.3);
}

.clipboard-icon {
  color: #00ffcc;
}

/* Settings - Clipboard profile section */
.clipboard-profile-section {
  margin-bottom: 2rem;
  padding-bottom: 1rem;
  border-bottom: 1px solid rgba(0, 255, 204, 0.2);
}

.clipboard-profile-row {
  background: rgba(0, 255, 204, 0.05);
  border: 1px solid rgba(0, 255, 204, 0.2);
  border-radius: 6px;
  padding: 12px 16px;
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.profile-info {
  display: flex;
  align-items: center;
  gap: 12px;
}

.profile-description {
  font-size: 0.875rem;
  opacity: 0.7;
  margin-left: auto;
}

.profile-status {
  display: flex;
  align-items: center;
  gap: 6px;
  font-size: 0.875rem;
  color: #10b981;
}

/* User profiles section */
.user-profiles-section .section-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 1rem;
}

.profile-count {
  font-size: 0.875rem;
  opacity: 0.7;
  background: rgba(0, 255, 204, 0.1);
  padding: 2px 8px;
  border-radius: 12px;
}

.add-profile-button:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}
```

### Profile Button Behavior
- [ ] **WHEN** app loads
- [ ] **THEN** Profile 1 shows clipboard icon (📋) instead of text
- [ ] **AND** Profile 1 tooltip shows "Clipboard - Direct copy"
- [ ] **AND** Profiles 2-5 show custom names or default placeholder

### Settings Interface
- [ ] **WHEN** settings are opened
- [ ] **THEN** Profile 1 appears in read-only section as "Always Available"
- [ ] **AND** Only profiles 2-5 appear in editable list
- [ ] **AND** Maximum 4 profiles can be configured
- [ ] **AND** "Add Profile" button shows current count (e.g., "Add Profile (2/4)")

### Drag-and-Drop Behavior
- [ ] **WHEN** user drags profiles in settings
- [ ] **THEN** Profile 1 (clipboard) is not draggable
- [ ] **AND** Profiles 2-5 can be reordered among themselves
- [ ] **AND** Profile 1 always stays in position 1

### Profile Selection Logic
- [ ] **WHEN** Profile 1 is selected
- [ ] **THEN** transcription copies directly without GPT-4 formatting
- [ ] **AND** profile appears visually distinct (clipboard styling)

## 🔗 Affected Components

**Files to modify:**
- `src/components/ProfileButtons.tsx` - Clipboard icon rendering
- `src/components/SettingsSheet.tsx` - Settings UI with 4-profile limit
- `src/contexts/ProfileContext.tsx` - Profile filtering logic
- `src/styles.css` - Clipboard profile styling
- `src-tauri/src/profile/` - Profile data structure updates

**UI Components:**
- Profile button grid (main interface)
- Settings overview page
- Profile editor (prevent editing Profile 1)
- Drag-and-drop system

## 🧪 Testing Strategy

- [ ] **Profile button rendering**: Verify clipboard icon vs text display
- [ ] **Settings filtering**: Ensure Profile 1 not in editable list
- [ ] **Drag-and-drop**: Test Profile 1 exclusion from reordering
- [ ] **Profile limit**: Verify maximum 4 user profiles + clipboard
- [ ] **Styling consistency**: Clipboard profile visual distinction
- [ ] **Backend integration**: Profile loading with clipboard profile

## 💡 Technical Notes

**Default Profile Creation:**
- Profile 1 always exists in the system
- Created automatically if missing during profile loading
- Cannot be deleted or edited through UI
- Always visible and available

**Profile Numbering:**
- Profile 1: System clipboard profile (fixed)
- Profiles 2-5: User-configurable (max 4)
- Profile IDs remain consistent for existing users

**Migration Strategy:**
- Existing users: Profile 1 converted to clipboard profile automatically
- New users: Profile 1 created as clipboard profile by default
- No data loss for existing custom profiles

**Performance Considerations:**
- Profile filtering done at context level for efficiency
- UI components receive pre-filtered profile lists
- Minimal re-renders when switching between profiles

## 🎨 UX Improvements

**Visual Hierarchy:**
- Clipboard profile clearly distinguished from custom profiles
- Consistent iconography (📋 for clipboard, text for custom)
- Color coding for different profile types

**User Guidance:**
- Clear separation between system and user profiles in settings
- Profile count indicator for remaining slots
- Helpful descriptions and tooltips

**Accessibility:**
- Proper ARIA labels for clipboard vs custom profiles
- Screen reader friendly profile type announcements
- Keyboard navigation respects profile distinctions

## 🏷️ Labels

`feature` `ui` `profiles` `ux` `priority:medium`

---

**Issue establishes intuitive profile system with dedicated clipboard option and streamlined custom profile management**
